[support] Add missing require for matcher_definition.rb in object_formatter.rb
```
$ pry
[1] pry(main)> require 'rspec/support'
=> true
[2] pry(main)> RSpec::Support.require_rspec_support 'object_formatter'
=> true
[3] pry(main)> RSpec::Support::ObjectFormatter.format(:foo)
NoMethodError: undefined method `is_a_matcher?' for RSpec::Support:Module
from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-support-3.4.1/lib/rspec/support/object_formatter.rb:36:in `prepare_for_inspection'
```